### ISSUE TITLE
Feature to create auto-generate fake data

### ISSUE THREAD

**Issue by marcosvidolin** [marcosvidolin/gload#1]
A feature that allows us to add random auto-generate fake data. YAML example:

```yaml
CreateUser:
  url: https://api.gloadsys.com/users
  mehotd: POST
  timeout: 5
  iterations: 50
  processes: 3
  headers:
    Content-Type: application/json
  body: |
    {
      "username": $GLOAD_USERNAME$,
      "email": $GLOAD_EMAIL$
    }
```

Idea:

read the yaml as a template and replace the keywords with random data using a lib like go-faker.

https://github.com/ddosify/go-faker
